- lib/defaultAdblockLists.js
Coin mining in the browser is sometimes abused and can lead to greater CPU usage, especially bad on mobile. 
I'm in favour of it.
> Block coin miners by default with Brave shields up

- lists/regions.h
Fanboy's Swedish is no longer maintained and has been for a year now thus we should replace it with Frellwit's Swedish Filter!
The new filter is way better and covers a much bigger area of Swedish sites and is updated with an interval of 3 days. (Sometimes even every day) It is not a fork or a new version of  Fanboy's Swedish but instead it is a totally standalone filterlist. It is the standard regional filterlist in Ublock Origin for Swedish users also.
cc @bbondy and @lukemulks
> Replace unsupported Fanboy's Swedish with Frellwit's Swedish Filter

- ad_block_client_wrap.cc
See https://github.com/brave/browser-laptop/issues/13092
It looks like this commit was needed in Muon in order to fix adblocking but this branch is behind master and thus the first step for fixing [#13092](https://github.com/brave/browser-laptop/issues/13092) in Browser-laptop 👍 
Be aware that this is not my commit so all cred goes to @hferreiro 👍
> Merge this commit as the first step in order to fix the Swedish ad blocking

- Makefile
Second call to node-gyp in build rule calls globally installed version rather than the one from node_modules.
> fix path of node-gyp in Makefile

- brave/BUILD.gn
- filter_list.cc
- filter_list.h
The Chromium Style Checker plugin was complaining about the complexity
of the inlined constructors when I started referencing the regional ad
block filter list on Windows.
More details here:
https://www.chromium.org/developers/coding-style/chromium-style-checker-errors
> Refactor filter_list slightly to appease Chromium style checker plugin

- ad_block_client_wrap.cc
- filter_list.cc
- filter_list.h
- lists/default.h
- lists/malware.h
- lists/regions.h
Associates the Brave AdBlock component IDs with their corresponding filters, allowing us to refer to all AdBlock metadata from one location.
> Add component id's to ad block filter lists

- muon/BUILD.gn
> Fix undefined definitions of "FilterList" and "isBlockableProtocol" for muon

- ad_block_client.cc
- ad_block_client.h
- ad_block_client_wrap.cc
- filter.cc
- filter.h
- protocol.cc
- test/binding.gyp
- test/js/matchingTest.js
- test/orig_filters_test.cc
added a bool flag to `AdBlockClient.prototype.parse` to control whether this data should be preserved (since otherwise the text of ~ the entire filter list would be preserved in the uncommon case of wanting to use `findMatchingFilters`).
If `true`, then the return value of `findMatchingFilters` will have `matchingOrigRule` and `matchingExceptionOrigRule` properties that have the original filter rule text.  If `false`, then the `matchingOrigRule` and `matchingExceptionOrigRule` properties are `undefined`
> Added option to preserve original filter text

- lib/util.js
- scripts/check.js
Updated the check.js script to return the full, original rule text when the `-D` option is provided.  
Required updating the lib/util.js methods to all accept an extra options param.  Made an option so that future possible parse options could be included in the object, instead of a trailing line of arguments.
> update the -D option on cli to return full original rule text

- filter.cc
- test/parser_test.cc
Basically reworked the string matching function, making it shorter
and simpler and added some tests.
Fix https://github.com/brave/ad-block/issues/150
> Fix incorrect handling of filters beginning with circumflex (^).

- ad_block_client.cc
- package-lock.json
- package.json
- test/js/matchingTest.js
Originally ad-block clients needed to calculate if the context option was 3p or 1p by itself and tell the ad-block lib that.  Later we moved that to matches, but we never checked it in find matching filters.  
We now automaticlaly calculate it for clients using this function:
Fix https://github.com/brave/ad-block/issues/166
> Find matching filters should check 3p context

- ad_block_client_wrap.cc
- test/js/serializationTest.js
Passing an invalid string (something that wasn't generated from `client.serialize`) to `client.deserialize` crashes node.  
This PR includes a test and fix
> add test and fix for passing an invalid serialized dat info to client deserialize

- ad_block_client.cc
- test/js/parsingTest.js
We were wrongly checking end of the input buffer to see if a filter was a regex, instead of the end of the filter.  So if the file ended in a slash then we would store a big regex of the length from the start of the regex to the end of the file as the regex itself, then continue parsing as usual from the next filter correctly.
If the last line ended with a newline it would always detect things to not be regexs.
This has no effect on clients since they don't parse things, they just use already created DAT files.
Fix https://github.com/brave/ad-block/issues/173
> Fix bug in regex parsing

- lists/regions.h
update the URL for the Bulgarian list to be HTTPS
> Only use HTTPS URLs for filter lists

- ad_block_client.cc
- ad_block_client.h
- test/parser_test.cc
Fix https://github.com/brave/ad-block/issues/180
> Add support for getting matched filter info in matches

- ad_block_client.cc
- ad_block_client_wrap.cc
- context_domain.cc
- context_domain.h
- filter.cc
- filter.h
- lists/CPPLINT.cfg
- lists/default.h
- protocol.cc
- test/orig_filters_test.cc
- test/parser_test.cc
Code fixes so that `npm run lint-cpp` returns with a success error code
> make cpp lint happy across the board

- lists/default.h
This fixes brave/adblock-lists#52.
I have build the `dat` file with this change and didn't see any errors in this list. I also tested the generated `dat` file in Beta and saw ads blocked on CNN, as expected.
If this is accepted, I'll file another PR to remove `ublock-unbreak.txt` from the `brave/adblock-lists` repo.
> Use upstream uBlock unbreak list directly (fixes brave/adblock-lists#52)

- lists/malware.h
Fixes #184.
I was able to generate the `SafeBrowsingData.dat` file without any errors.
> Use a maintained Spam404 repo (fixes #184)

- ad_block_client.cc
See also:
https://github.com/brave/brave-core/pull/1813
See also:
https://github.com/brave/brave-browser/issues/3535
Basically this will only set the `FOThirdParty` and `FONotThirdParty` flags internally if we didn't specify them when calling `match`.
This is to get past a problem where the library doesn't calculate it correctly with an easy fix in brave-core.
> Only determine third-party when needed

- no_fingerprint_domain.cc
- test/js/matchingTest.js
Back several months ago when we added EasyPrivacy support we added a perf optimization to make that possible for domain only host anchored filters. 
This is stored last in the serialization file, so we didn't see any fallout.
The situation is described more in the issue below.
FIx https://github.com/brave/ad-block/issues/190
> Fix deserialized host anchored domain only filter matching

- ad_block_client.cc
Fix https://github.com/brave/ad-block/issues/195
> Make ad-block tag serialization compatible with old version

- ad_block_client_wrap.cc
- filter.cc
- filter.h
- lib/filtering.js
- test/js/filteringTest.js
- test/parser_test.cc
Fix https://github.com/brave/brave-browser/issues/3749
Related PR: https://github.com/brave/brave-core/pull/1981
> Add an option to cancel a request

- package-lock.json
- package.json
- test/js/filterListTest.js
Once `node-gyp` issues a release, we can back this out and update. The version number for that will likely be `3.8.1`
More info at: https://github.com/nodejs/node-gyp/pull/1713
> Temporarily fix https://www.npmjs.com/advisories/803
